# fly.toml app configuration file generated for salasblog2 on 2025-06-23T21:25:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'salasblog2'
primary_region = 'bos'

[build]

[env]
  PORT = '8080'
  # Git configuration for blog post persistence
  GIT_EMAIL = 'blog-api@salasblog2.com'
  GIT_NAME = 'Salasblog2 API'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  max_machines_running = 2
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '5s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
