#!/usr/bin/env python3
# draft_generator.py — Generate blog draft posts from raindrop data using Claude API
# Author: Pito Salas and Claude Code
# Open Source Under MIT license

import logging
from datetime import date
from pathlib import Path

import anthropic
import requests
import yaml
from bs4 import BeautifulSoup

logger = logging.getLogger(__name__)

def _load_model() -> str:
    for candidate in [Path(__file__).parent.parent.parent / "config.yaml", Path("config.yaml")]:
        if candidate.exists():
            with open(candidate) as f:
                data = yaml.safe_load(f) or {}
            return data.get("drafts", {}).get("claude_model", "claude-sonnet-4-6")
    return "claude-sonnet-4-6"

CLAUDE_MODEL = _load_model()
URL_FETCH_TIMEOUT = 5
MAX_FETCHED_CHARS = 3000


def fetch_url_text(url: str) -> str:
    """Fetch plain text from a URL, returning empty string on any failure."""
    try:
        resp = requests.get(url, timeout=URL_FETCH_TIMEOUT, headers={"User-Agent": "Mozilla/5.0"})
        resp.raise_for_status()
        resp.encoding = resp.apparent_encoding or "utf-8"
        soup = BeautifulSoup(resp.text, "html.parser")
        for tag in soup(["script", "style", "nav", "footer"]):
            tag.decompose()
        text = soup.get_text(separator=" ", strip=True)[:MAX_FETCHED_CHARS]
        return text.encode("ascii", errors="ignore").decode("ascii")
    except requests.RequestException as e:
        logger.warning("Could not fetch %s: %s", url, e)
        return ""


def _ascii(text: str) -> str:
    return text.encode("ascii", errors="ignore").decode("ascii")


def build_prompt(drop: dict, page_text: str) -> str:
    tags = ", ".join(drop.get("tags") or []) or "none"
    note = _ascii(drop.get("note") or "")
    excerpt = _ascii(drop.get("excerpt") or "")
    page_section = f"\n\nPage content (first {MAX_FETCHED_CHARS} chars):\n{page_text}" if page_text else ""

    return f"""Write a single short blog paragraph (50-75 words maximum) about the following link post.
The paragraph must include a markdown hyperlink to the source URL.
Write in first person as the blog author sharing an interesting find.
End naturally — no meta-commentary, no sign-off.

Title: {_ascii(drop['title'])}
URL: {drop['url']}
Domain: {_ascii(drop['domain'])}
Tags: {tags}
Excerpt: {excerpt}
My note: {note}{page_section}

Output only the paragraph text (plain markdown), nothing else."""


def build_frontmatter(drop: dict, title: str) -> str:
    data = {
        "title": title,
        "date": date.today().isoformat(),
        "type": "blog",
        "draft": True,
        "author": "Claude.ai",
        "source_raindrop": drop["filename"],
        "source_url": drop["url"],
        "tags": drop.get("tags") or [],
    }
    return "---\n" + yaml.dump(data, allow_unicode=True, default_flow_style=False, encoding=None) + "---\n"


def call_claude(prompt: str) -> str:
    client = anthropic.Anthropic()
    message = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=150,
        messages=[{"role": "user", "content": prompt}],
    )
    return message.content[0].text.strip()


def generate_draft_from_drop(drop: dict) -> str:
    """Generate a markdown draft blog post from a raindrop dict.

    Returns full file content (frontmatter + body) ready to write to disk.
    """
    page_text = fetch_url_text(drop["url"])
    logger.info("Fetched page text length: %d", len(page_text))
    prompt = build_prompt(drop, page_text)
    logger.info("Calling Claude API...")
    try:
        body = call_claude(prompt)
    except Exception as e:
        logger.error("Claude API call failed: %s: %s", type(e).__name__, e)
        raise
    logger.info("Claude response length: %d", len(body))
    title = drop["title"]
    fm = build_frontmatter(drop, title)
    prefix = f"_Generated by AI based on a [link]({drop['raindrop_url']}) saved on {drop['date']}_\n\n"
    return fm + "\n" + prefix + body + "\n"


def save_draft(content: str, filename: str, blog_dirs: list[Path]) -> None:
    """Write draft content to each directory in blog_dirs."""
    for blog_dir in blog_dirs:
        blog_dir.mkdir(parents=True, exist_ok=True)
        (blog_dir / filename).write_text(content, encoding="utf-8")
