name: Claude Code

on:
  workflow_dispatch:
    inputs:
      direct_prompt:
        description: 'Request for Claude'
        required: true
        type: string

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anthropics/claude-code-action@beta
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: ${{ github.event.inputs.direct_prompt }}