name: Claude Code

on:
  workflow_dispatch:
    inputs:
      claude_request:
        description: 'Request for Claude'
        required: true
        type: string

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_request: ${{ github.event.inputs.claude_request }}